@startuml

box "Liquidity Deposit User Flow" #grey
participant "Liquidity Provider" as LP
participant "Mettalex liquidity Providing UI" as LPUI
participant "MetaMask" as MM
participant "Mettalex Liquidity Vault Smart Contract" as LVSM

end box

note over LP #lightgreen: **LP Token Balance**: \nX USDT
note over LVSM #lightblue: **Mettalex Liquidity Token Balance**: \nY USDT

LP -> LPUI: Enter Mettalex Liquidity section. Choose commodity to provide liquidity with.
LPUI ->> LPUI: Insert the amount of liquidity to be deposited.
LPUI -// MM: Deposit request sent to MetaMask.
MM ->> MM: Accept the transaction receipt.
...
MM -->> LVSM: Call Deposit Function of Mettalex Liquidity Vault: **deposit(uint _amount)**. Funds are deposited into the Liquidity Vault.

note over LP #lightgreen: **LP Token Balance**: \n0 USDT
note over LVSM #lightblue: **Mettalex Liquidity Token Balance**: \nX+Y USDT

group "other Liquidity Deposit APIs"
MM <<-->> LVSM: **getPricePerFullShare()**
MM <<-->> LVSM: **earn()**

end group

@enduml